name: test ci

on:
  push:
    branches: ["main"]

env:
  PROJECT_NAME: Test-Project

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get Git tag name
        id: commit
        uses: pr-mpt/actions-commit-hash@v2

      - name: Get commit messages
        run: |
          COMMIT_MESSAGES=""
          commits="${{ toJSON(github.event.commits) }}"
          echo "${commits}"
          length=$(jq length <<< "${commits}")
          echo "${length}"
