name: build-hook-image

on:
  push:
    branches:
        - main
env:
  TEST_TAG: st-baas/quorum-k8s-hooks:test

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker
          buildkitd-config-inline: |
            [registry."${{ vars.REGISTRY_URL }}"]
              http = true
              insecure = true

      # - name: Add Insecure Docker Registry
      #   run: |
      #     sudo truncate -s-2 /etc/docker/daemon.json
      #     echo ", \"insecure-registries\": [\"${{ vars.REGISTRY_URL }}\"]}" | sudo tee -a /etc/docker/daemon.json
      #     sudo systemctl restart docker

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Export to Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}
    
      - name: Test Image before Push
        run: |
          docker run --rm ${{ env.TEST_TAG }}

      - name: Build and Push to Registry
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/hooks/Dockerfile
          push: false
          tags: st-baas/quorum-k8s-hooks:${{ steps.commit.outputs.short }}
