name: build-hook-image

on:
  push:
    branches:
        - main
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          # buildkitd-config: .github/buildkitd.toml
          config-inline: |
            [registry."${{ vars.REGISTRY_URL }}"]
              http = true
              insecure = true

      - name: Check buildx config
        run: |
          cat /etc/buildkit/buildkitd.toml

      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ vars.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push to registry
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/hooks/Dockerfile
          push: false
          # tags: st-baas/quorum-k8s-hooks:${{ steps.commit.outputs.short }}

      # - name: Inspect
      #   run: |
      #     docker buildx imagetools inspect ${{ secrets.REGISTRY_URL }}/st-baas/quorum-k8s-hooks:latest
