name: build-hook-image

on:
  push:
    branches:
        - main

env:
  FILE: src/hooks/Dockerfile
  BASE_TAG: pulse/besu-k8s-hooks
  TEST_TAG: pulse/besu-k8s-hooks:test
  VERSION_TAG: qgt-0.2.16

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Add Insecure Docker Registry
        run: |
          sudo truncate -s-2 /etc/docker/daemon.json
          echo ", \"insecure-registries\": [\"${{ vars.REGISTRY_URL }}\"]}" | sudo tee -a /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # - name: Build and Export to Docker
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     file: ${{ env.FILE }}
      #     load: true
      #     tags: ${{ env.TEST_TAG }}
      
      # - name: Test Image before Push
      #   run: |
      #     docker run --rm ${{ env.TEST_TAG }}

      - name: Build and Push to Registry
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ env.FILE }}
          push: true
          tags: ${{ vars.REGISTRY_URL }}/${{ env.BASE_TAG }}:${{ env.VERSION_TAG }}
