name: Docker Build (smart-contract-verifier)

on:
  push:
    branches:
      - 'main'

env:
  BASE_TAG: pulse/blockscout-smart-contract-verifier
  VERSION_TAG: v1.8.0

jobs:
  push:
    name: Docker build and docker push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-config-inline: |
            [registry."${{ vars.REGISTRY_URL }}"]
              http = true
              insecure = true

      - name: Add Insecure Docker Registry
        run: |
          sudo truncate -s-2 /etc/docker/daemon.json
          echo ", \"insecure-registries\": [\"${{ vars.REGISTRY_URL }}\"]}" | sudo tee -a /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "smart-contract-verifier"
          file: "smart-contract-verifier/smart-contract-verifier-server/Dockerfile"
          push: false
          tags: ${{ vars.REGISTRY_URL }}/${{ env.BASE_TAG }}:${{ env.VERSION_TAG }}
